language: node_js
env:
  global:
  - secure: liFB8GQivcVInBqpsr/reWK3iFni8V5NhQ8Pj2hKZOf8kjBF9R+HP2/dZF71jnpz3RUvWZwEiI0XCxVVItA7piq/TFobsmHaWCr4Jl24atkaC+3uS92rB9PdA9vNEJo4khxl/Ng0vEuTEskMQazgcra7yjSAE/pBl2a/jKXYAcfz0tLL38yx907wlbJhyQwh5gIVJ5Jmku46E3WsOO2E+tsJJ91vlLaNiVoiPIw/j7udrzDPDR4hPQsB2CukbiAtz8OYdlEwXcZvYPaYxAd08GpEIJ3R6Jy/i4vZXRtd8Fl8OaebXPutPGXi192KSz5cQiu68S0V0Bn6yB4qCw9lt4McsZ+ZdUjqNbL2+9EB+fIyyqf5/T8w+RPJjphMGbUfR43fIQKZ1ZAM7nu6vOVU/jPgpsfWgxYFDumhOxF/5XD4YJQKOuVF6Ggd/DHmwhAe/DR56XKScfT38cB/3cqh8cPumczw7Q+9gRBnAUS680E2UtLDGQVRGlfRD+dL/Fm9G7yPXL2Ny61Jm7YzO8FQ7pqjcgM9MhmCuUYC7jN30l4FgXeyTqvVBfYY3+k0Xqb2qUkbeTiZb72BUkllZyFtEEd8YSIz3qpCxFZ3HLY4/6a7o8FrYh9vU3aMTP5/igxmENNCcOtKqDivm4stiZaGluCV/SW+kTAOGl+khs8865E=
  - secure: W6cEIYtTUtRhEshAlfohcBT3FmbaxlkeC0asvXWimdCmxq3OBcn6rV0Rv5kaZllzyYQznvopFz/fmuowEewc9r2n5Yt2/HaaebqMJRocnI0X1htfYZzEsQI1UvG7xyRe+seVB/xBoyZLXHNwcMOe9YAWyWBvLy7Trpv/zHPy8+5pZbuGizWpQSDqe7SiUQre+Ru5hB4R3giyK0/UA2gMjBB5NhnrIyD9K7wt25CX3RgfiP5E2PqpSBimG9ecMPZMBgURazNhgwkrgFU/08kq8pU5H8aP3oW2RHfP+VouLpeZP7slHw9eIf3azuzjsDdYR2pei7IZqi/8mfvvjFeKmNQ1TNkG7NV9uv89GlJbeRWfVj7WdKcBG+oIsLGR0B3L/d4ZxvrUw/OcfPdtjt9zIrs8gsEi26Cw79W7J0glhHm3re7cBR5JjE8yMXNsN2gYQGbGA9Ybmdx1RCjLjNmCewTWt+uH1w2Hhr4axZvfk8xOZ6MtwE2vgSa3JnpFxWAXwLT9sSwrSvd2gDKqiF+tH+yVmJgUoI/7dzdIpO1Ucrn0/Y5iZDVvYJY6v8yO+FzFD1RmteZm5K5nux/nNoS2ifQ+/ZU2Sl6wFZ8rsI22wphsgnLTNyH4t/DQ+e+MdSAKGdFcrOp18p14AuBCKYnCWeI7Pw6Q08FCc+vGDlt/4Sc=
addons:
  ssh_known_hosts:
  - dbr.me
cache:
  directories:
  - node_modules
  yarn: true
notifications:
  email: false
node_js:
- '6'
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_install:
- openssl aes-256-cbc -K $encrypted_70266334fac6_key -iv $encrypted_70266334fac6_iv
  -in deploy_rsa.enc -out deploy_rsa -d
before_deploy:
- openssl aes-256-cbc -K $encrypted_70266334fac6_key -iv $encrypted_70266334fac6_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- yarn build
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r -q $TRAVIS_BUILD_DIR/build/ $DEPLOY_USER@dbr.me:$DEPLOY_PATH
  on:
    branch: master
