language: node_js
cache:
  directories:
    - node_modules
install: true
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
after_success:
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
